MovieRegistr/Models/ErrorViewModel.cs
using System;

namespace MovieRegistr.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieRegistr/Models/MovieRegistration/AddMovieFormViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieRegistr.Models.MovieRegistration
{
    public class AddMovieFormViewModel
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }

        public int Year { get; set; }

        public string Actors { get; set; }

        public string Directors { get; set; }

        public double Runtime { get; set; }
    }
}

MovieRegistr/Models/MovieRegistration/AddMovieResultViewModel.cs
using MovieRegistr.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieRegistr.Models
{
    public class AddMovieResultViewModel
    {
        public List<Movie> Movies { get; set; }

    }
}

MovieRegistr/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MovieRegistr.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MovieRegistr.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieRegistr/Controllers/MovieRegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using MovieRegistr.DALModels;
using MovieRegistr.Models;
using MovieRegistr.Models.MovieRegistration;
using MovieRegistr.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieRegistr.Controllers
{
    public class MovieRegistrationController : Controller
    {
        private readonly IMovies _movieList;
        private readonly MovieContext _movieListContext;

        public MovieRegistrationController(IMovies movies, MovieContext movieContext)
        {
            _movieList = movies;
            _movieListContext = movieContext;
        }

        public IActionResult AddMovieForm()
        {
            return View();
        }

        public IActionResult AddMovieResult(AddMovieFormViewModel model)
        {
            var movie = new MovieDAL();
            movie.MovieId = model.ID;
            movie.Title = model.Title;
            movie.Genre = model.Genre;
            movie.Runtime = model.Runtime;

            _movieListContext.Movies.Add(movie);

            _movieListContext.SaveChanges();

           var viewModel = new AddMovieResultViewModel();
            var movies = _movieListContext.Movies.ToList();

            //need to do LINQ stuff here 

            return View(viewModel);
        }



    }
}

MovieRegistr/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MovieRegistr/Views/MovieRegistration/AddMovieForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model MovieRegistr.Models.MovieRegistration.AddMovieFormViewModel


<form asp-controller="MovieRegistration" asp-action="AddMovieResult" method="post">

    <label asp-for="ID"></label>
    <input asp-for="ID" />

    <label asp-for="Title"></label>
    <input asp-for="Title" />

    <label asp-for="Genre"></label>
    <input asp-for="Genre" />

    <label asp-for="Year"></label>
    <input asp-for="Year" />

    <label asp-for="Actors"></label>
    <input asp-for="Actors" />

    <label asp-for="Directors"></label>
    <input asp-for="Directors" />

    <button>Add Movie</button>

</form>

MovieRegistr/Views/MovieRegistration/AddMovieResult.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model MovieRegistr.Models.AddMovieResultViewModel

<ul class="list-group">

    @foreach (var movie in Model.Movies)
    {
    <li class="list-group-item">

        <p>Movie @movie.Title has been registered</p>

        <p>ID: @movie.ID</p>
        <p>Title: @movie.Title</p>
        <p>Genre: @movie.Genre</p>
        <p>Year: @movie.Year</p>
        <p>Actors: @movie.Actors</p>
        <p>Directors: @movie.Directors</p>

        <a asp-controller="MovieRegistration" asp-action="AddMovieForm">Add Another Movie</a>

    </li>
    }

</ul>

MovieRegistr/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieRegistr</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieRegistr</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MovieRegistration" asp-action="AddMovieForm">Movie Registration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieRegistr - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>